[versions]
agp = "9.5.0-alpha08"
kotlin = "2.5.0-Beta1"
composeBom = "2026.10.00"
activityCompose = "1.14.0-alpha03"
lifecycle = "2.12.0-alpha04"
okhttp = "5.5.0"
kotlinxCoroutines = "1.11.0"
kotlinxSerialization = "1.12.0-RC"
gplayapi = "3.6.4"
asm = "9.10.1"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom-alpha", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
aurora-gplayapi = { group = "com.auroraoss", name = "gplayapi", version.ref = "gplayapi" }
asm-bom = { group = "org.ow2.asm", name = "asm-bom", version.ref = "asm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
